### ISSUE TITLE
Error on 1.11.2

### ISSUE THREAD

**Issue by arturek1666** [Rsl1122/PluginFolderSwapper#1]
[21:04:13] [Server thread/ERROR]: Error occurred while enabling PFS v1.1.0 (Is it up to date?)
java.lang.NullPointerException
	at com.djrapitops.pfs.PFS.loadPlugins(PFS.java:83) ~[?:?]
	at com.djrapitops.pfs.PFS.onEnable(PFS.java:42) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [patched_1.11.2.jar:git-Paper-1021]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209) [patched_1.11.2.jar:git-Paper-1021]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.2.jar:git-Paper-1021]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

My Config:
# PFS | Plugin Folder Swapper - Config
# PluginPaths - Exact filepath to the plugins
PluginPaths:
- /minigry/

I can't do c:/something/something as my host doesn't give me that information so i only have /minigry/ I hope that's not what couzing the issue

**Comment by AuroraLS3** [comment]
Issue has been solved (v1.1.1)  by adding %serverfolder% placeholder that will be replaced with the folder your spigot.yml is located in.
https://www.spigotmc.org/resources/pfs-plugin-folder-swapper.34336/
